/* 
 * File:   CUIButton.cpp
 * Author: karsten
 * 
 * Created on 3. august 2011, 16:30
 */

#include "CUIButton.h"

CUIButton::CUIButton(CUIBaseFrame* parrent):
CUIFrame(parrent)
{
	_icon = Icontex::Invalid;
	_x = 0;
	_y = 0;
	_wight = 40;
	_hight = 40;
	
}

CUIButton::CUIButton(CUIBaseFrame* parrent,uint32_t x, uint32_t y,uint32_t wight, uint32_t hight):
CUIFrame(parrent)
{
	_icon = Icontex::Invalid;
	_x = x;
	_y = y;
	_wight = wight;
	_hight = hight;
	_UIlevel = 3;

}

void CUIButton::Click(SDL_Event event,int32_t x, int32_t y){
	//if (x >= this->x && x <= this->x+this->wight && y >= this->y && y <= this->y+this->hight){
		cerr<<"click button"<<endl;
		
	//}
}

void CUIButton::Draw(){
	int32_t uvx1;
	int32_t uvy1;
	int32_t wight;
	int32_t hight;
	uint32_t sheetsize;
	if (this->_icon != Icontex::Invalid){
		sheetsize = 1024;
		switch (this->_icon){

		//*****************************************
		//file generated by python spritesheet
		#include "../Textures/Icons/cords.txt"

		//**************************************************
			default:{
			glBindTexture( GL_TEXTURE_2D, textures[Textures::IconSheet]);
			wight = 0;
			hight = 0;
			uvx1 = 0;
			uvy1 = 0;
			cerr<<"Warning subiconsheed tex"<<endl;
			break;
			}
		}


		glLoadIdentity();
		glTranslated((GLfloat)(_parrent->getX()+ _x),(GLfloat)(_parrent->getY()+ _y),0);

		glBegin( GL_QUADS );
		//Bottom-left vertex (corner)
		glTexCoord2f((((double)1)/sheetsize)*(uvx1), (((double)1)/sheetsize)*(uvy1) );
		glVertex3f(0, 0, 0.0f);

		//Bottom-right vertex (corner)
		glTexCoord2f((((double)1)/sheetsize)*(uvx1+wight), (((double)1)/sheetsize)*(uvy1) );
		glVertex3f(_wight, 0, 0.f);

		//Top-right vertex (corner)
		glTexCoord2f((((double)1)/sheetsize)*(uvx1+wight), (((double)1)/sheetsize)*(uvy1+hight) );
		glVertex3f(_wight, _hight, 0.f);

		//Top-left vertex (corner)
		glTexCoord2f((((double)1)/sheetsize)*(uvx1), (((double)1)/sheetsize)*(uvy1+hight) );
		glVertex3f(0, _hight, 0.f);
		glEnd();


	}else
		Drawbox(_x+_parrent->getX(),_y+_parrent->getY(),_wight,_hight,0,0,1,1);
}

CUIButton::~CUIButton() {
}

